[project]
name = "lecroy9300-speki"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jds6600>=1.1.1",
    "matplotlib>=3.10.7",
]
